name: flutter_logcat
description: A beautiful log client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  r_get_ip: ^0.1.1
  provider:
  dropdown_below: ^1.0.1
  shelf: ^1.2.0
  pretty_json: ^2.0.0

  # local database
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  # Freezed Usage : flutter pub run build_runner build [--delete-conflicting-outputs]
  freezed: ^0.14.1+3
  freezed_annotation:
  json_serializable:
  json_annotation:
  build_runner: ^2.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKrRegular.ttf
        - asset: assets/fonts/NotoSansKrThin.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKrBold.ttf
          weight: 700
